#!/usr/bin/env bash

# Brew setup first!
export PATH="$HOME/.brew/bin:/opt/homebrew/bin:$PATH"

# Silence warning on MacOS.
export BASH_SILENCE_DEPRECATION_WARNING=1

# Set vim mode.
set -o vi

for rcfile in $HOME/.config/dotfiles/shellrc/*; do
  [ -f "$rcfile" ] && source $rcfile
done

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[ -x "$(which brew)" ] && [ -f "$(brew --prefix fzf)/shell/completion.bash" ] && source "$(brew --prefix fzf)/shell/completion.bash"
[ -x "$(which brew)" ] && [ -f "$(brew --prefix fzf)/shell/key-bindings.bash" ] && source "$(brew --prefix fzf)/shell/key-bindings.bash"

# Rust me one more time!
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
