tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

cask "alfred"
cask "discord"
cask "divvy"
cask "docker"
cask "firefox"
cask "font-meslo-for-powerline"
cask "font-meslo-nerd-font"
cask "hyperswitch"
cask "iterm2"
cask "lastpass"
cask "outline-manager"
cask "outline"
cask "spectacle"
cask "visual-studio-code"

brew "git"
brew "httpie"
brew "python"
brew "tmux"
brew "wget"
