#!/usr/bin/env bash

# Ubuntu default prompt.
export PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "

# Silence warning on MacOS.
export BASH_SILENCE_DEPRECATION_WARNING=1

# Set vim mode.
set -o vi

for rcfile in $HOME/.config/shellrc/*; do
  if [[ -z "$DEBUG" ]]; then
    [ -f ${rcfile} ] && source $rcfile
  else
    echo "Sourcing ${rcfile}..."
    start=$(date +%s)
    [ -f ${rcfile} ] && source $rcfile
    echo "Finished in: $(expr $(date +%s) - $start) seconds"
  fi
done

[ -z "$DEBUG" ] || echo "~/.fzf.bash"
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[ -z "$DEBUG" ] || echo "fzf bash completion"
[ -x "$(which brew)" ] && [ -f "$(brew --prefix fzf)/shell/completion.bash" ] && source "$(brew --prefix fzf)/shell/completion.bash"
[ -z "$DEBUG" ] || echo "fzf keybindings"
[ -x "$(which brew)" ] && [ -f "$(brew --prefix fzf)/shell/key-bindings.bash" ] && source "$(brew --prefix fzf)/shell/key-bindings.bash"

[ -z "$DEBUG" ] || echo "bash completion"
[ -x "$(which brew)" ] && [[ -r "$(brew --prefix bash-completion)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix bash-completion)/etc/profile.d/bash_completion.sh"
