#!/usr/bin/env bash
# If running interactively, do not do anything.
[[ -z "$DEBUG" ]] || echo "Checking interactive"
[[ ! -o interactive ]] && return

# Brew setup first!
export PATH="$HOME/.brew/bin:/opt/homebrew/bin:$PATH"

shellrc="${XDG_CONFIG:-$HOME/.config}/dotfiles/shellrc"
[[ -d "$shellrc" ]] || exit 1
for rcfile in $(find "$shellrc/" -type f -o -type l | sort -n); do
  source "$rcfile"
done

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -x "$(which brew)" ] && [ -f "$(brew --prefix fzf)/shell/completion.zsh" ] && source "$(brew --prefix fzf)/shell/completion.zsh"

# Comes late for tab-completing CDPATH.
autoload -Uz compinit promptinit
compinit

#########
# vi mode
#########

bindkey -v

# switch to command mode with jj
bindkey '^j' vi-cmd-mode

# `v` is already mapped to visual mode, so we need to use a different key to
# open Vim
bindkey -M vicmd "^V" edit-command-line

# Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
export KEYTIMEOUT=1

# incremental search in insert mode
bindkey "^F" history-incremental-search-forward
bindkey "^R" history-incremental-search-backward

# beginning search with arrow keys and j/k
# bindkey "^[OA" up-line-or-beginning-search
# bindkey "^[OB" down-line-or-beginning-search
# bindkey -M vicmd "k" up-line-or-beginning-search
# bindkey -M vicmd "j" down-line-or-beginning-search

# beginning search in insert mode, redundant with the up/down arrows above
# but a little easier to press.
bindkey "^P" history-search-backward
bindkey "^N" history-search-forward

# incremental search in vi command mode
bindkey -M vicmd '?' history-incremental-search-backward
bindkey -M vicmd '/' history-incremental-search-forward
# navigate matches in incremental search
bindkey -M viins '^R' history-incremental-pattern-search-backward
bindkey -M viins '^F' history-incremental-pattern-search-forward


[[ -z "$DEBUG" ]] || echo "Loading fzf custom key-bindings"
if [[ -n "$FZF" ]]; then
  bindkey "^R" fzf-history-widget
  bindkey "^T" fzf-file-widget
  bindkey -M vicmd '?' fzf-history-widget
  bindkey -M viins "^R" fzf-history-widget
  bindkey -M viins "^t" fzf-file-widget
fi
