#!/usr/bin/env bash

export DOTFILES_PATH="$HOME/.config/dotfiles"
export PATH="$HOME/bin:$HOME/.config/dotfiles/bin:$HOME/.brew/bin:$HOME/go/bin:$HOME/.rbenv/bin:$PATH"
export CDPATH="$HOME:$HOME/code/:$HOME/code/github/:$HOME/code/github/exegeteio/:$HOME/code/gitlab/:$HOME/Desktop/"
if [ ! -z "$WORKSPACE" ]; then
  export CDPATH="$WORKSPACE:$WORKSPACE/code/:$WORKSPACE/code/github/:$WORKSPACE/code/github/exegeteio/:$WORKSPACE/code/gitlab/:$WORKSPACE/Desktop/"
fi

# Prettier Docker commands, parallel builds.
export DOCKER_BUILDKIT=1

# Allow connect back to rails from inside Docker.
export RAILS_DEVELOPMENT_HOSTS=host.docker.internal,localhost,.ngrok.io

# Only set the port if not already set.  Good for devcontainers.
[[ -z "$PORT" ]] && export PORT=3000

# Setup Golang
export GOPATH=$HOME/code/go
export GOBIN=$GOPATH/bin
export PATH=$GOBIN:$PATH
