#!/usr/bin/env bash

if [[ -x "$(which tmux)" ]] && [[ -z "$TMUX" ]] && [[ -f "$HOME/.auto_tmux" ]] && [[ -z "$VSCODE_PID" ]] && [[ "$TERM_PROGRAM" != "vscode" ]] && [[ -z "$INTELLIJ_ENVIRONMENT_READER" ]] && [[ -z "$FIG_JETBRAINS_SHELL_INTEGRATION" ]]; then
  if [[ -z "$SSH_CLIENT" ]]; then
    exec tmux.re "main"
  else
    exec tmux.re "$(whoami)"
  fi
fi
