#!/usr/bin/env bash

# [[ -n "$(which oh-my-posh)" ]] && eval "$(oh-my-posh init zsh)" # --config ${XDG_CONFIG_HOME}/dotfiles/omp.json)"

export PS1="%1~ ↣ "

if [ ! -z "$ZSH_VERSION" ]; then
  autoload -Uz vcs_info
  precmd () { vcs_info }
  zstyle ':vcs_info:*' formats ' %F{green}%b%f'
  setopt PROMPT_SUBST
  export PROMPT='%1~${vcs_info_msg_0_} ↣ '
fi
