#!/usr/bin/env bash

# Set up SSH Agent
# Poached from:  https://code.visualstudio.com/docs/remote/containers#_using-ssh-keys
if [ -d "$HOME/.ssh" ]; then
  [[ -z "$DEBUG" ]] || echo "Initializing ssh-agent"
  if [ -z "$SSH_AUTH_SOCK" ]; then
    # Check for a currently running instance of the agent
    [ -z "$SSH_AGENT_PID" ] && source "$HOME/.ssh/ssh-agent"
    _agent="$(ps -p "$SSH_AGENT_PID" &>-)"
    if [ -z "$?" ]; then
      echo "Launging new SSH Agent..."
      # Launch a new instance of the agent
      ssh-agent -s &> ~/.ssh/ssh-agent
      source $HOME/.ssh/ssh-agent
    fi
  fi
  _keys="$(ssh-add -l)"
  if [ "$?" = "1" ]; then
    echo "No SSH keys found in ssh-agent"
    # ssh-add
  fi
fi

