#!/usr/bin/env bash

# Set up SSH Agent
# Poached from:  https://code.visualstudio.com/docs/remote/containers#_using-ssh-keys
if [ -d "$HOME/.ssh" ]; then
  if [ -z "$SSH_AGENT_PID" ]; then
    # Check for a currently running instance of the agent
    [[ -z "$DEBUG" ]] || echo "Sourcing agent file"
    source "$HOME/.ssh/ssh-agent"
  fi

  # If not present, use 0.
  _agent="$(ps -p "${SSH_AGENT_PID:-0}")"
  # "1" is is the exit code when the pid is not found.
  if [ "1" -eq "$?" ]; then
    echo "Launching new SSH Agent..."
    # Launch a new instance of the agent
    ssh-agent -s | grep -v "echo" &> ~/.ssh/ssh-agent
    source $HOME/.ssh/ssh-agent
  fi

  _keys="$(ssh-add -l)"
  if [ "$?" = "1" ]; then
    echo "No SSH keys found in ssh-agent"
    # ssh-add
  fi
fi

