#!/usr/bin/env bash

[ -z "$DEBUG" ] || echo "Setting up fzf options..."
if [[ -f "~/.fzf.$RBENV_SHELL" ]]; then
  export FZF="$(which fzf)"
  source "$HOME/.fzf.$RBENV_SHELL"
fi
if [[ -z "$TMUX" ]]; then
  export FZF_TMUX_OPTS=""
else
  export FZF_TMUX_OPTS="-p 75%"
fi
[ -z "$DEBUG" ] || echo "Done setting up fzf options..."
