#!/bin/bash

[[ -z "$DEBUG" ]] || echo "Loading fzf"
if [[ -f "~/.fzf.$RBENV_SHELL" ]]; then
  FZF="$(which fzf)"
  source "$HOME/.fzf.$RBENV_SHELL"
fi
export FZF
[[ -z "$TMUX" ]] || export FZF_TMUX_OPTS="-p 40%"

