#!/usr/bin/env bash
[ -z "$DEBUG" ] || echo "Setting up EDITOR..."
if [ -z "$EDITOR" ]; then
  # RubyMine if available
  if [[  ! -z "$IDEA_INITIAL_DIRECTORY" ]]; then
    type=$(echo $__CFBundleIdentifier | sed 's/.*\.//' | tr '[:upper:]' '[:lower:]')
    if [[ -x "$(which "$type")" ]]; then
      echo "Using $type for editor"
      export EDITOR="$type"
      export EDITOR_ARGS="rubymine.args"
    fi
  # VS Code if available.
  elif [ "$TERM_PROGRAM" = "vscode" ]; then
    export EDITOR='code -wr'
    export EDITOR_ARGS='code.args'
  # Neovim
  elif [ -x "$(which nvim)" ]; then
    export EDITOR='nvim'
    export EDITOR_ARGS='vi.args'
  # World's best fallback.
  else
    export EDITOR='vim'
    export EDITOR_ARGS='vi.args'
  fi
fi

if [[ -z "$1" ]]; then
  # No argument, skip this!
elif [ "$1" = "rubymine" ]; then
  export EDITOR='rubymine'
  export EDITOR_ARGS='rubymine.args'
# VS Code if available.
elif [ "$1" = "code" ]; then
  export EDITOR='code -wr'
  export EDITOR_ARGS='code.args'
# Neovim
elif [ "$1" = "nvim" ]; then
  export EDITOR='nvim'
  export EDITOR_ARGS='vi.args'
# World's best fallback.
elif [ "$1" = "vim" ]; then
  export EDITOR='vim'
  export EDITOR_ARGS='vi.args'
else
  echo "Must choose one of:  rubymine, code, nvim, vim"
fi

[ -z "$DEBUG" ] || echo "Done setting up EDITOR..."
