#!/usr/bin/env bash

[ -z "$DEBUG" ] || echo "Setting up aliases..."
alias gf="git fetch --all -p"
alias less="less -r"
alias ll="ls -lh"
alias ls="ls --color=always"
alias :q="exit"
alias r="$HOME/.config/dotfiles/bin/r" # To override shell builtin.
alias grep="rg"
[ -x "$(which bat)" ] && alias less="bat --plain"
[ -z "$DEBUG" ] || echo "Done setting up aliases..."
