#!/usr/bin/env bash

alias '?'=duck
alias '??'=google
alias a="source aliases"
alias gf="git fetch --all -p"
alias less="less -r"
alias ll="ls -lh"
alias ls="ls --color=auto"
alias phish="http --follow -p hH"
alias :q="exit"
alias r="$HOME/.config/dotfiles/bin/r" # To override shell builtin.
